# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            IDleg
tagline:          'Blog documenting development of a new Idaho Legislative Portal for CS 597 at Boise State'
description:      Using hyde theme http://hyde.getpoole.com
url:              http://idleg.org
baseurl:          /

author:
  name:           'Nathaniel Hoffman'
  url:            https://twitter.com/paleomedia

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/paleomedia/idleg
  
