# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            IDleg
tagline:          'An Idaho legislative portal'
description:      A blog documenting development of a new Idaho Legislative Portal for CS 597 at Boise State
url:              http://idleg.info
baseurl:          /idleg

author:
  name:           'Nathaniel Hoffman'
  url:            https://twitter.com/paleomedia

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/paeleomedia
  repo:           https://github.com/paleomedia/idleg
  
